Feat/api
tynopet/adidas-shop-frontend pull request #12
Opened 2017-06-04 15:51 UTC by tynopet

Пока не придумал как отсортировать фильтр (и по алфавиту и по цифрам), и не подгонял под адаптив.

2017-06-04 17:21 UTC, imevro requested changes

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +      <SizeTitle onClick={() => onClick(null)}>SIZE</SizeTitle>
Не надо так делать

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +        <Button type="button" key={size} onClick={() => onClick(size)} selected={size === filter}>
isSelected

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +import 'whatwg-fetch';
В index.js корневой, тут это ни к чему

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +const buildStaticUrl = ({ id, fileName }, height) =>
В helpers директорию

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +  handleFilterClick(filter) {
handleFilterChange

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +        this.setState({ shoes, filterSizes, filteredShoes: shoes });
Не понял смысла

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +      const filteredShoes = filter ? shoes.filter(({ sizes }) => sizes.includes(filter)) : shoes;
Убери тернарник

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +      shoes: [],
Нет смысла хранить shoes и filteredShoes. Лучше храни оригинальный массив (shoes), а в выводе оперируй `shoes.filter().map()`

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +      filter: null,
filterBySize

2017-06-04 17:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +      filterSizes: [],
sizes?

2017-06-04 19:52 UTC, tynopet commented on src/Products/List/index.jsx
> +        this.setState({ shoes, filterSizes, filteredShoes: shoes });
Это я из ответа прохожу по каждому товару, и формирую из всех sizes массив размеров. Set для того чтобы не повторялись размеры

2017-06-04 22:32 UTC, imevro requested changes

2017-06-04 22:32 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +      <SizeTitle onClick={() => onClick('*')}>SIZE</SizeTitle>
Передавай null или undefined

2017-06-04 22:32 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +        const filterSizes = items
Добавь отступов, сложно читать

2017-06-04 22:32 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +        this.setState({ shoes, sizes: filterSizes });
И тут тоже

2017-06-04 22:32 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +    fetch(`https://erodionov-adidas-fake-api.now.sh/v1${match.url}`)
https://github.com/cyberhazard/adidas-shop-frontend/pull/12#discussion_r120022496

2017-06-04 22:32 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +        const shoes = items.map(({ id, price, title, images, sizes }) => ({
Вынеси лучше в функцию типа `transformInputValues` в корень продактс

2017-06-05 21:27 UTC, imevro requested changes

2017-06-05 21:27 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +    this.setState(state => ({ filterBySize: filter === state.filterBySize ? null : filter }));
не понял проверку

2017-06-05 21:27 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +            filter={this.state.filterBySize || ''}
почему пустая строка

2017-06-05 21:27 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +                  (this.state.filterBySize ? sizes.includes(this.state.filterBySize) : true),
не понял проверку

2017-06-07 13:14 UTC, imevro requested changes

2017-06-07 13:14 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +            isSelected={selected}
isSelected={selected}?

2017-06-07 13:14 UTC, evgenyrodionov commented on src/helpers/index.js
> +export const buildSizes = items => (
чё-то пиздец сложно

2017-06-07 15:40 UTC, imevro approved these changes

2017-06-07 15:40 UTC, merged