fix: pre-production-fixes (final boss)
tynopet/adidas-shop-frontend pull request #15
Opened 2017-06-07 22:41 UTC by tynopet

2017-06-07 23:30 UTC, tynopet commented
Ночью now залагал, не смог заалиасить. Ссылка на последний деплой https://build-bxlpneihnh.now.sh
Надеюсь что к мержу пр-а, если он произойдет now отлагает и все будет хорошо)

2017-06-08 13:24 UTC, imevro requested changes

2017-06-08 13:24 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +import { Container, Image, SizeWrapper, SizeTitle, Button, ModalWrapper } from './styled-components';
назови просто styled  afqk

2017-06-08 13:24 UTC, evgenyrodionov commented on src/helpers/index.js
> +export const sortSizes = (a, b) => {
Сложно, упростить

2017-06-08 13:24 UTC, evgenyrodionov commented on src/helpers/index.js
> +export const calcImageSize = (category) => {
убрать

2017-06-08 13:24 UTC, evgenyrodionov commented on src/helpers/index.js
>  export const transformInputArray = items => items
переделать в transformInputValues и использовать как products.map(product => transformInputValues(product))

2017-06-08 13:24 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +          {Object.entries(sortObjectByKeys(this.props.sizes))
нихуя непонятно

2017-06-08 13:24 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +    this.setState(state => ({ showSizes: !state.showSizes }));
prevState

2017-06-08 13:24 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +  handleShowClick() {
handle show click?

2017-06-08 13:24 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +          {Object.keys(this.props.sizes).length > calcFilterLength() && <Button type="button" onClick={this.handleShowClick}>{'>>'}</Button>}
бля какой ад тут происходит

2017-06-09 16:10 UTC, imevro requested changes

2017-06-09 16:10 UTC, evgenyrodionov commented on src/Products/List/Filter/index.jsx
> +  handleExpanderClick() {
это дропдаун

2017-06-09 16:10 UTC, evgenyrodionov commented on src/api.js
>  export const fetchShoes = match => fetch(`https://erodionov-adidas-fake-api.now.sh/v1${match.url}`)
поч shoes-то кстати

2017-06-09 16:10 UTC, evgenyrodionov commented on src/api.js
>      const filterSizes = collectInputSizes(items);
поч не sizes

2017-06-09 16:10 UTC, evgenyrodionov commented on src/api.js
>  export const fetchShoe = match => fetch(`https://erodionov-adidas-fake-api.now.sh/v1${match.url}`)
ну и опять же

2017-06-09 16:10 UTC, evgenyrodionov commented on src/api.js
>  export const fetchShoe = match => fetch(`https://erodionov-adidas-fake-api.now.sh/v1${match.url}`)
и да зачем ты тут передаёшь match

2017-06-09 16:10 UTC, evgenyrodionov commented on src/helpers/index.js
> +  // Не знаю как упростить сильнее функцию сортировки, поэтому оставлю комментарии
на английский

2017-06-10 14:23 UTC, imevro approved these changes

2017-06-10 14:23 UTC, merged