Feat/class components submenu
tynopet/adidas-shop-frontend pull request #7
Opened 2017-05-22 10:46 UTC by tynopet

2017-05-22 18:46 UTC, imevro requested changes
Фикси

2017-05-22 18:46 UTC, evgenyrodionov commented on src/Sidebar/Submenu/index.jsx
> +      opened: false,
isOpen

2017-05-22 18:46 UTC, evgenyrodionov commented on src/Sidebar/Submenu/index.jsx
> +import { SubmenuContainer, SubmenuTitle, SubmenuWrapper } from './styled-components';
Нейминг пиздец

2017-05-22 18:46 UTC, evgenyrodionov commented on src/Sidebar/Submenu/index.jsx
> +        <SubmenuWrapper opened={this.state.opened}>
Не рендерь вообще компонент, если isOpen false

2017-05-22 18:46 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
> +        <NavLink exact to="/basketball/shoes" submenu>SHOES</NavLink>
Зачем проп сабменю?

2017-05-23 21:03 UTC, tynopet commented on src/Sidebar/index.jsx
> +        <NavLink exact to="/basketball/shoes" submenu>SHOES</NavLink>
Тут не очень понял - как тогда название разворачиваемого пункта передавать?

2017-05-24 08:21 UTC, imevro requested changes

2017-05-24 08:21 UTC, evgenyrodionov commented on src/Sidebar/Submenu/index.jsx
> +        <Title onClick={this.handleClick} isOpen={this.state.isOpen}>{title}</Title>
Это кнопка

2017-05-24 08:21 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
> +        <NavLink exact to="/basketball/shoes" submenu>SHOES</NavLink>
Я про проп сабменю у навлинка

2017-05-24 11:30 UTC, evgenyrodionov commented
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

2017-05-24 11:47 UTC, imevro approved these changes

2017-05-24 11:48 UTC, imevro requested changes

2017-05-24 11:48 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
>      <NavWrapper>
Пазве что тут назови просто Nav

2017-05-24 11:48 UTC, merged